"""Refresh prices/api.yaml: OpenRouter's public per-provider prices + hand-checked extras.

    uv run --with pyyaml --with httpx scripts/update_api_prices.py

OpenRouter lists each provider serving a model with its own input/output price and quantization
(GET https://openrouter.ai/api/v1/models/<slug>/endpoints, no key needed). Providers it doesn't
carry are kept in prices/api_manual.yaml. Run weekly by CI; review the diff like any data change.
"""

from __future__ import annotations

import sys
from datetime import UTC, datetime
from pathlib import Path

import httpx
import yaml

ROOT = Path(__file__).resolve().parents[1]
PRICES = ROOT / "prices"
ENDPOINTS = "https://openrouter.ai/api/v1/models/{slug}/endpoints"


def openrouter_offers(hf_id: str, slug: str, today: str) -> list[dict]:
    resp = httpx.get(ENDPOINTS.format(slug=slug), timeout=30)
    resp.raise_for_status()
    offers = []
    for e in resp.json()["data"]["endpoints"]:
        pricing = e["pricing"]
        prompt, completion = float(pricing["prompt"]), float(pricing["completion"])
        if prompt <= 0 and completion <= 0:
            continue  # free tiers are rate-limited promotions, not a price you can plan on
        quant = e.get("quantization")
        offers.append({
            "model": hf_id,
            "provider": e["provider_name"],
            "usd_per_1m_input": round(prompt * 1e6, 6),
            "usd_per_1m_output": round(completion * 1e6, 6),
            "quantization": None if quant in (None, "unknown") else quant,
            "context_length": e.get("context_length"),
            "source": f"https://openrouter.ai/{slug}/providers",
            "fetched_at": today,
        })
    return offers


def main() -> int:
    today = datetime.now(UTC).date().isoformat()
    model_map = yaml.safe_load((PRICES / "model_map.yaml").read_text())
    offers: list[dict] = []
    for hf_id, slug in model_map.items():
        try:
            found = openrouter_offers(hf_id, slug, today)
        except httpx.HTTPError as e:
            print(f"{hf_id}: OpenRouter fetch failed ({e}); keeping previous rows", file=sys.stderr)
            old = yaml.safe_load((PRICES / "api.yaml").read_text()) or {}
            found = [o for o in old.get("offers", [])
                     if o["model"] == hf_id and "openrouter.ai" in o["source"]]
        print(f"{hf_id}: {len(found)} OpenRouter providers")
        offers += found
    manual = yaml.safe_load((PRICES / "api_manual.yaml").read_text()) or {}
    seen = {(o["model"], o["provider"].lower()) for o in offers}
    for o in manual.get("offers", []):
        if (o["model"], o["provider"].lower()) not in seen:  # live price wins over manual
            offers.append({**o, "fetched_at": str(o["fetched_at"])})
    offers.sort(key=lambda o: (o["model"], o["usd_per_1m_output"], o["provider"]))
    header = ("# GENERATED by scripts/update_api_prices.py: edit prices/api_manual.yaml or "
              "prices/model_map.yaml instead.\n")
    body = yaml.safe_dump({"generated_at": today, "offers": offers}, sort_keys=False,
                          allow_unicode=True, width=120)
    (PRICES / "api.yaml").write_text(header + body)
    print(f"wrote {len(offers)} offers to prices/api.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
